<?php
/**
 * Created by PhpStorm.
 * User: lin2ur
 * Date: 2016/9/20
 * Time: 下午6:56
 */

namespace app\filters;
use yii\base\ActionFilter;

class Microtime extends ActionFilter
{
    public $startTime;

    public function beforeAction($action)
    {
        $this->startTime = microtime(true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        echo microtime(true) - $this->startTime;
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

}